#!/bin/bash
# ============================================================================
# clean-example.sh - Reset example project to initial state
# ============================================================================
#
# RESPONSIBILITY:
#   Removes all generated artifacts, deletes the internal git repository,
#   and restores state files to their initial template state.
#   Use this to re-run expert execution from scratch.
#
# USAGE:
#   ./scripts/clean-example.sh <project-dir>
#
# ARGUMENTS:
#   <project-dir>  Path to example project (e.g., examples/finance-tracker)
#
# WHAT IT CLEANS:
#   - .git/             (internal git repository)
#   - docs/**/*.md      (generated artifacts)
#   - questions/*.md    (blocker files)
#   - CREW_COMPLETE     (termination signal)
#   - .gitignore        (generated by init-example.sh)
#   - INDEX.md          (restored from main repo)
#   - .noodlecrew/tasks.md (restored from main repo)
#
# EXAMPLES:
#   ./scripts/clean-example.sh examples/finance-tracker
#
# ============================================================================

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Parse arguments
PROJECT_DIR="$1"

if [[ -z "$PROJECT_DIR" ]]; then
    echo -e "${RED}Error:${NC} Missing project directory" >&2
    echo "Usage: $0 <project-dir>" >&2
    exit 1
fi

# Resolve to absolute path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

if [[ ! "$PROJECT_DIR" = /* ]]; then
    PROJECT_DIR_REL="$PROJECT_DIR"
    PROJECT_DIR="$ROOT_DIR/$PROJECT_DIR"
else
    PROJECT_DIR_REL="${PROJECT_DIR#$ROOT_DIR/}"
fi

if [[ ! -d "$PROJECT_DIR" ]]; then
    echo -e "${RED}Error:${NC} Directory not found: $PROJECT_DIR" >&2
    exit 1
fi

echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  NoodleCrew - Clean Example${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Project: $PROJECT_DIR"
echo ""

# 1. Remove internal git repository
echo -e "${YELLOW}[1/5]${NC} Removing internal git repository..."
if [[ -d "$PROJECT_DIR/.git" ]]; then
    rm -rf "$PROJECT_DIR/.git"
    rm -f "$PROJECT_DIR/.gitignore"
    echo "       Removed .git/ and .gitignore"
else
    echo "       No internal git repo found"
fi

# 2. Remove generated artifacts in docs/
echo -e "${YELLOW}[2/5]${NC} Cleaning docs/**/*.md..."
DOCS_DIR="$PROJECT_DIR/docs"
if [[ -d "$DOCS_DIR" ]]; then
    ARTIFACT_COUNT=0
    while IFS= read -r -d '' f; do
        echo "       Removing: ${f#$PROJECT_DIR/}"
        rm -f "$f"
        ((ARTIFACT_COUNT++)) || true
    done < <(find "$DOCS_DIR" -name "*.md" -type f -print0 2>/dev/null)

    if [[ $ARTIFACT_COUNT -eq 0 ]]; then
        echo "       No artifacts found"
    fi
fi

# 3. Remove blocker files
echo -e "${YELLOW}[3/5]${NC} Cleaning questions/*.md..."
QUESTIONS_DIR="$PROJECT_DIR/questions"
if [[ -d "$QUESTIONS_DIR" ]]; then
    BLOCKER_COUNT=0
    while IFS= read -r -d '' f; do
        echo "       Removing: ${f#$PROJECT_DIR/}"
        rm -f "$f"
        ((BLOCKER_COUNT++)) || true
    done < <(find "$QUESTIONS_DIR" -name "*.md" -type f -print0 2>/dev/null)

    if [[ $BLOCKER_COUNT -eq 0 ]]; then
        echo "       No blockers found"
    fi
fi

# 4. Remove CREW_COMPLETE
echo -e "${YELLOW}[4/5]${NC} Removing CREW_COMPLETE..."
if [[ -f "$PROJECT_DIR/CREW_COMPLETE" ]]; then
    rm -f "$PROJECT_DIR/CREW_COMPLETE"
    echo "       Removed"
else
    echo "       Not present"
fi

# 5. Restore state files from main repo
echo -e "${YELLOW}[5/5]${NC} Restoring state files from main repo..."

cd "$ROOT_DIR"

# Restore INDEX.md
if git ls-files --error-unmatch "$PROJECT_DIR_REL/INDEX.md" &>/dev/null; then
    git checkout -- "$PROJECT_DIR_REL/INDEX.md" 2>/dev/null && echo "       Restored: INDEX.md" || echo "       INDEX.md: already clean"
else
    echo "       INDEX.md: not tracked (skipped)"
fi

# Restore tasks.md
if git ls-files --error-unmatch "$PROJECT_DIR_REL/.noodlecrew/tasks.md" &>/dev/null; then
    git checkout -- "$PROJECT_DIR_REL/.noodlecrew/tasks.md" 2>/dev/null && echo "       Restored: .noodlecrew/tasks.md" || echo "       tasks.md: already clean"
else
    echo "       tasks.md: not tracked (skipped)"
fi

echo ""
echo -e "${GREEN}Done.${NC} Example project reset to initial state."
echo ""
echo "To start fresh:"
echo "  1. Initialize: ./scripts/init-example.sh $PROJECT_DIR_REL"
echo "  2. Run expert: ./scripts/run-expert.sh product-owner $PROJECT_DIR_REL"
echo ""
