#!/bin/bash
# ============================================================================
# init-example.sh - Initialize an example project for crew execution
# ============================================================================
#
# RESPONSIBILITY:
#   Prepares an example project for crew execution by initializing a git
#   repository inside it. This allows experts to make commits that are
#   isolated from the main noodle-crew repository.
#
# USAGE:
#   ./scripts/init-example.sh <project-dir>
#
# ARGUMENTS:
#   <project-dir>  Path to example project (e.g., examples/finance-tracker)
#
# WHAT IT DOES:
#   1. Validates the project has required files (IDEA.md, INDEX.md, tasks.md)
#   2. Initializes a git repository inside the project
#   3. Creates initial commit with template files
#   4. Project is now ready for expert execution
#
# EXAMPLES:
#   ./scripts/init-example.sh examples/finance-tracker
#
# EXIT CODES:
#   0 - Success (or already initialized)
#   1 - Invalid arguments
#   2 - Directory not found
#   3 - Required files missing (IDEA.md)
#
# SEE ALSO:
#   - run-expert.sh (execute experts after init)
#   - clean-example.sh (reset to initial state)
#
# ============================================================================

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Parse arguments
PROJECT_DIR="$1"

if [[ -z "$PROJECT_DIR" ]]; then
    echo -e "${RED}Error:${NC} Missing project directory" >&2
    echo "Usage: $0 <project-dir>" >&2
    exit 1
fi

# Resolve to absolute path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

if [[ ! "$PROJECT_DIR" = /* ]]; then
    PROJECT_DIR="$ROOT_DIR/$PROJECT_DIR"
fi

if [[ ! -d "$PROJECT_DIR" ]]; then
    echo -e "${RED}Error:${NC} Directory not found: $PROJECT_DIR" >&2
    exit 1
fi

# Check for required files
if [[ ! -f "$PROJECT_DIR/IDEA.md" ]]; then
    echo -e "${RED}Error:${NC} IDEA.md not found in $PROJECT_DIR" >&2
    exit 1
fi

echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  NoodleCrew - Initialize Example${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Project: $PROJECT_DIR"
echo ""

# Check if already initialized
if [[ -d "$PROJECT_DIR/.git" ]]; then
    echo -e "${YELLOW}Warning:${NC} Project already has a git repository."
    echo "         Use clean-example.sh first if you want to reset."
    echo ""
    exit 0
fi

# Initialize git
echo -e "${YELLOW}[1/2]${NC} Initializing git repository..."
cd "$PROJECT_DIR"
git init --quiet

# Create .gitignore for the example project
cat > .gitignore << 'EOF'
# OS files
.DS_Store

# Generated by NoodleCrew (optional - keep if you want history)
# Uncomment to ignore generated artifacts:
# docs/**/*.md
# questions/*.md
# CREW_COMPLETE
EOF

# Initial commit
echo -e "${YELLOW}[2/2]${NC} Creating initial commit..."
git add .
git commit --quiet -m "chore: initialize project from NoodleCrew template"

echo ""
echo -e "${GREEN}Done.${NC} Project initialized with git repository."
echo ""
echo "Next steps:"
echo "  1. Run an expert:"
echo "     ./scripts/run-expert.sh product-owner ${PROJECT_DIR#$ROOT_DIR/}"
echo ""
echo "  2. View commit history:"
echo "     cd ${PROJECT_DIR#$ROOT_DIR/} && git log --oneline"
echo ""
echo "  3. To reset and start over:"
echo "     ./scripts/clean-example.sh ${PROJECT_DIR#$ROOT_DIR/}"
echo ""
